---
title: "Scenario 1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


<iframe width='1000px' height='1258px' src='https://deseret-access-mapping.herokuapp.com/' >
</iframe>

<br>
Year 2080 regional development including the Orange County Sector Plan was developed using a variety of metrics, the theoretical framework used are described below
<br>

<br>
Place holder text
<br>

# Evaluation {.tabset .tabset-fade .tabset-pills}

## Socioeconomic Forecast 

Place Holder Text

## Environment

number of impacted environmental acres and ecosystems    

## Land Capacities / Place Types

regional urban footprint, development densities, balance of uses, percent of population in walkable communities, etc. 

## Transportation / Accessibility 

regional accessibility by mode, multimodal system performance, mode share, roadway delay, etc.

## Economic Development

economic productivity, regional gross domestic product, average regional income, etc. 

## Fiscal impacts

tax and fee revenues generated, infrastructure costs, service costs, net fiscal balance, etc.  
